name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install deps (frontend)
        run: npm ci --prefix frontend
      - name: Build (frontend)
        run: npm run build --prefix frontend

  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install deps (backend)
        run: npm ci --prefix backend
      - name: Verify env placeholders
        run: |
          test -f backend/.env.example
          echo "Backend dependencies installed."


