name: Deploy to VPS

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Ambiente para deploy'
        required: true
        default: 'production'
        type: choice
        options:
        - production
        - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install Frontend Dependencies
      working-directory: ./frontend
      run: npm ci
      
    - name: Build Frontend
      working-directory: ./frontend
      run: npm run build
      
    - name: Install Backend Dependencies
      working-directory: ./backend
      run: npm ci
      
    - name: Build Backend Image
      working-directory: ./backend
      run: |
        docker build -t weavecode-backend:${{ github.sha }} .
        docker tag weavecode-backend:${{ github.sha }} weavecode-backend:latest
        
    - name: Test Backend
      working-directory: ./backend
      run: |
        npm test || echo "Tests failed but continuing with deploy"
        
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.VPS_SSH_KEY }}
        
    - name: Add VPS to known hosts
      run: |
        ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts
        
    - name: Deploy to VPS
      run: |
        echo "🚀 Iniciando deploy para VPS..."
        
        # Criar arquivo de deploy temporário
        cat > deploy.sh << 'EOF'
        #!/bin/bash
        set -e
        
        echo "📥 Recebendo deploy do GitHub Actions..."
        
        cd /opt/weavecode
        
        # Backup antes do deploy
        echo "💾 Criando backup..."
        ./backup-postgres.sh
        
        # Parar serviços
        echo "⏹️ Parando serviços..."
        docker-compose down
        
        # Pull das imagens mais recentes
        echo "📥 Baixando imagens mais recentes..."
        docker-compose pull
        
        # Iniciar serviços
        echo "▶️ Iniciando serviços..."
        docker-compose up -d
        
        # Aguardar serviços ficarem prontos
        echo "⏳ Aguardando serviços ficarem prontos..."
        sleep 30
        
        # Verificar saúde
        echo "🔍 Verificando saúde dos serviços..."
        ./health-check.sh
        
        # Verificar se tudo está funcionando
        if curl -f http://localhost:4000/health > /dev/null 2>&1; then
          echo "✅ Deploy concluído com sucesso!"
          echo "🌐 Site disponível em: http://${{ secrets.VPS_HOST }}"
        else
          echo "❌ Deploy falhou - backend não está respondendo"
          exit 1
        fi
        EOF
        
        # Enviar script para VPS
        scp deploy.sh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/opt/weavecode/
        
        # Executar deploy na VPS
        ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'SSH_EOF'
          cd /opt/weavecode
          chmod +x deploy.sh
          ./deploy.sh
        SSH_EOF
        
        echo "✅ Deploy concluído com sucesso!"
        
    - name: Health Check
      run: |
        echo "🔍 Verificando saúde dos serviços..."
        sleep 60  # Aguardar serviços ficarem prontos
        
        # Verificar se o backend está respondendo
        if curl -f http://${{ secrets.VPS_HOST }}:4000/health > /dev/null 2>&1; then
          echo "✅ Backend está funcionando!"
        else
          echo "❌ Backend não está respondendo"
          exit 1
        fi
        
        # Verificar se o site está acessível
        if curl -f http://${{ secrets.VPS_HOST }} > /dev/null 2>&1; then
          echo "✅ Site está acessível!"
        else
          echo "❌ Site não está acessível"
          exit 1
        fi
        
    - name: Notify Success
      if: success()
      run: |
        echo "🎉 Deploy concluído com sucesso!"
        echo "Commit: ${{ github.sha }}"
        echo "Branch: ${{ github.ref_name }}"
        echo "VPS: ${{ secrets.VPS_HOST }}"
        echo "Ambiente: ${{ inputs.environment || 'production' }}"
        
    - name: Notify Failure
      if: failure()
      run: |
        echo "❌ Deploy falhou!"
        echo "Commit: ${{ github.sha }}"
        echo "Branch: ${{ github.ref_name }}"
        echo "VPS: ${{ secrets.VPS_HOST }}"
        echo "Verifique os logs para mais detalhes"
        
    - name: Cleanup
      if: always()
      run: |
        echo "🧹 Limpando arquivos temporários..."
        rm -f deploy.sh
